// react_firebase_auth/src/components/Navigation.tsx
import { Link } from 'react-router-dom'
import { logOut } from '../firebase/authMethode'
import { useAppData } from '../context/appContext'
import { USER_LOGIN, USER_NOT_LOGIN } from '../context/actions'

function Navigation() {
  const appState = useAppData()

  return (
    <nav className='shadow-lg flex justify-between items-center p-5'>
      <Link to='/' className='font-black text-3xl'>
        React Firebase Auth
      </Link>
      <div className='flex items-center gap-4 font-semibold'>
        <Link to='/home' className='btn-text'>
          Home
        </Link>
        {appState?.state.user.userLoginState === USER_NOT_LOGIN ? (
          <Link to='/' className='btn-text'>
            Login
          </Link>
        ) : null}

        {appState?.state.user.userLoginState === USER_LOGIN ? (
          <button onClick={() => logOut()} className='btn px-5'>
            Logout
          </button>
        ) : null}
      </div>
    </nav>
  )
}

export default Navigation

// angular_firebase_auth/src/app/navigation/navigation.component.ts
import { Component, OnInit } from '@angular/core';
import { AngularFireAuth } from '@angular/fire/auth';
import { Router } from '@angular/router';
import { Observable } from 'rxjs';

@Component({
  selector: 'app-navigation',
  templateUrl: './navigation.component.html',
})
export class NavigationComponent implements OnInit {
  public user$: Observable<any> | undefined;
  constructor(public auth: AngularFireAuth, public router: Router) {}

  ngOnInit(): void {
    this.user$ = this.auth.user;
  }

  async logoutFn() {
    await this.auth.signOut();
    this.router.navigate(['']);
  }
}

<nav class="shadow-lg flex justify-between items-center p-5">
  <a routerLink="/" class="font-black text-3xl">Angular Firebase Auth </a>
  <div class="flex items-center gap-4 font-semibold">
    <a routerLink="/home" class="btn-text"> Home </a>
    <a *ngIf="!(user$ | async)" routerLink="/" class="btn-text"> Login </a>
    <button (click)="logoutFn()" class="btn px-5">Logout</button>
  </div>
</nav>
